version: '3.8'
services:
  flask-container:
    build: ./
    container_name: flask-container
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - 8088:8088

  postgresql-container:
    image: postgres:14
    container_name: postgresql-container
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5432:5432'
    volumes:
      - postgresql_vol:/var/lib/postgresql/data

volumes:
  postgresql_vol: